Assignment 1 - Playlist which works with Non-explicit and explicit tracks
binalee21/Assignment pull request #1
Opened 2023-05-15 17:13 UTC by binalee21

2023-05-17 06:21 UTC, Shreya76 requested changes

2023-05-17 06:21 UTC, Shreya76 commented on cypress/integration/createPlaylist.js
> +        cy.get('button.ant-btn > .ng-star-inserted').click();
Please add assertions after every action.

2023-05-17 06:21 UTC, Shreya76 commented on cypress/integration/createPlaylist.js
> +        //image selection
Please create custom commands for methods which can be reused.

2023-05-17 06:21 UTC, Shreya76 commented on cypress/integration/createPlaylist.js
> +        //publish playlist and verify
create multiple test cases for different functionalities.

2023-05-18 19:03 UTC, binalee21 commented on cypress/integration/createPlaylist.js
> +        //publish playlist and verify
added more assertions, custom commands and break into multiple testcases.

2023-05-22 14:42 UTC, merged