Move track order
binalee21/Assignment pull request #3
Opened 2023-05-17 14:08 UTC by binalee21

2023-05-19 07:22 UTC, Shreya76 requested changes

2023-05-19 07:22 UTC, Shreya76 commented on cypress/integration/moveTrackOrder.js
> +            cy.get('playlist-tracks')
We can keep this verification outside the if else block, so we don't have to repeat the code.

2023-05-19 08:13 UTC, binalee21 commented
changes done - verification code outside the if block.

2023-05-19 08:14 UTC, binalee21 commented on cypress/integration/moveTrackOrder.js
> +            cy.get('playlist-tracks')
changes done - verification code outside the if block.

2023-05-26 07:52 UTC, binalee21 commented
> @binalee21 Please resolve conflicts

Done

2023-05-30 10:25 UTC, Shreya76 approved these changes

2023-05-30 10:26 UTC, merged